
package com.yf.springwebservice.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImpl", targetNamespace = "WSDL")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "WSDL", className = "wsdl.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "WSDL", className = "wsdl.SaveResponse")
    @Action(input = "WSDL/WebServiceImpl/saveRequest", output = "WSDL/WebServiceImpl/saveResponse")
    public String save(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "WSDL", className = "wsdl.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "WSDL", className = "wsdl.SayHelloResponse")
    @Action(input = "WSDL/WebServiceImpl/sayHelloRequest", output = "WSDL/WebServiceImpl/sayHelloResponse")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
